use_bpm 120
bruh = "C:/Users/samuel_biner/Downloads/bruh.wav"
G5 = "C:/Users/samuel_biner/Downloads/cheating.wav"
C5 = "C:/Users/samuel_biner/Downloads/cheating1.wav"
B5 = "C:/Users/samuel_biner/Downloads/cheating2.wav"
E5 = "C:/Users/samuel_biner/Downloads/cheating3.wav"






print sample_duration G5
print sample_duration C5
print sample_duration B5
print sample_duration E5
#sample slowbruh

live_loop :righthand do
  use_synth :piano
  #first three measures
  3.times do
    sleep 1
    sample G5
    sleep 1
    sample G5
    sleep 1
    sample G5
    sleep 1
  end
  #fourth measure
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  #fifth measure
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  #sixth measure
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  #seventh measure
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  #eight measure
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  sample G5
  sleep 1
  #ninth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  play :D5
  sleep 1
  #tenth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  play :D5
  sleep 1
  #eleventh measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  play :D5
  sleep 1
  #twelfth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  sample B5
  sleep 1
  #thirteenth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  play :D5
  sleep 1
  #fourteenth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  play :D5
  sleep 1
  #fifteenth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  play :D5
  sleep 1
  #sixteenth measure
  play :C6
  sleep 1
  sample B5
  sleep 0.5
  sample G5
  sleep 1.5
  sample B5
  sleep 0.5
  play :C6
  sleep 0.5
  2.times do
    #seventeenth measure
    play :A4
    sample C5
    sleep 0.5
    play :A4
    sample C5
    sleep 1.5
    sample C5
    play :E5
    sample G5
    sleep 0.75
    sample C5
    play :E5
    sample G5
    sleep 0.75
    #eighteenth measure
    sample C5
    play :E5
    play :G4
    sleep 1.5
    sample C5
    play :E5
    play :G4
    sleep 0.5
    sample C5
    play :E5
    play :G4
    sleep 0.75
    play :G4
    play :B4
    play :D5
    sleep 0.75
    play :A4
    sample C5
    sleep 0.5
    #ninteenth measure
    play :A4
    sample C5
    play :E4
    sleep 0.5
    play :A4
    sample C5
    play :E4
    sleep 1.5
    play :A4
    sample C5
    sleep 0.5
    sample C5
    play :A5
    play :F5
    sleep 0.75
    sample G5
    play :E5
    sample C5
    sleep 0.75
    #twentieth measure
    sample C5
    play :E5
    sleep 1
    sample C5
    play :E5
    sleep 0.5
    sample C5
    play :E5
    sleep 0.5
    sample C5
    play :F5
    sleep 0.5
    sample C5
    play :E5
    sleep 0.5
    sample C5
    sample G5
    sleep 0.5
    sample C5
    play :E5
    sleep 0.5
    #twenty-first measure
    play :A4
    sample C5
    sleep 0.5
    play :A4
    sample C5
    sleep 1.5
    play :A4
    sample C5
    sleep 0.5
    sample C5
    play :E5
    sample G5
    sleep 0.75
    sample C5
    play :F5
    play :A5
    sleep 0.75
    #twenty-second measure
    play :E5
    sample C5
    play :G4
    sleep 1.5
    play :E5
    sample C5
    play :G4
    sleep 0.5
    play :E5
    sample C5
    play :G4
    sleep 0.75
    play :G4
    play :B4
    play :D5
    sleep 0.75
    play :A4
    sample C5
    sleep 0.5
    #twenty-third measure
    play :A4
    sample C5
    play :E4
    sleep 0.5
    play :A4
    sample C5
    play :E4
    sleep 1.5
    play :A4
    sample C5
    sleep 0.5
    sample C5
    play :A5
    play :F5
    sleep 0.75
    sample G5
    play :E5
    sample C5
    sleep 0.75
    #twenty-fourth measure
    sample C5
    play :E5
    sleep 1
    sample C5
    play :E5
    sleep 0.5
    sample C5
    play :E5
    sleep 0.5
    sample C5
    play :F5
    sleep 0.5
    sample C5
    play :E5
    sleep 0.5
    sample C5
    play :G4
    sleep 0.5
    play :A4
    play :G4
    sleep 0.5
  end
  #twenty-fifth measure
  stop
end

live_loop :lefthand do
  use_synth :piano
  #first measure
  play :B1
  play :E2
  sleep 1.5
  play :B2
  play :E2
  sleep 2.5
  #second measure
  play :G2
  play :E2
  play :B1
  sleep 1.5
  play :B1
  play :D2
  sleep 1.5
  play :B1
  play :C2
  sleep 1
  #third measure
  play :A1
  play :E2
  sleep 1.5
  play :E2
  play :B2
  sleep 1.5
  play :A2
  play :C3
  sleep 1
  #fourth measure
  play :B2
  play :G2
  play :E2
  sleep 1
  play :G2
  sleep 0.5
  play :F2
  play :D2
  sleep 1.5
  play :B1
  play :C2
  sleep 1
  #fifth measure
  play :B1
  play :E2
  sleep 1.5
  play :B2
  play :E2
  sleep 2.5
  #sixth measure
  play :G2
  play :E2
  play :B1
  sleep 1.5
  play :B1
  play :D2
  sleep 1.5
  play :B1
  play :C2
  sleep 1
  #seventh measure
  play :A1
  play :E2
  sleep 1.5
  play :E2
  play :B2
  sleep 1.5
  play :A2
  play :C3
  sleep 1
  #eight measure
  play :E2
  play :G2
  play :B2
  sleep 1
  play :G2
  sleep 0.5
  play :B2
  play :D3
  sleep 1.5
  play :B2
  play :E3
  sleep 1
  #ninth measure
  play :C1
  play :B1
  play :E2
  sleep 1.5
  play :A1
  play :E2
  play :B2
  sleep 2.5
  #tenth measure
  play :G1
  play :B1
  play :E2
  play :G2
  sleep 1.5
  play :D2
  play :B1
  play :B0
  sleep 1.5
  play :B0
  play :B1
  play :C2
  sleep 1
  #eleventh measure
  play :E2
  play :A1
  play :E1
  sleep 1.5
  play :E2
  play :A1
  play :B2
  sleep 1.5
  play :A2
  play :C3
  play :A1
  sleep 1
  #twelfth measure
  play :G1
  play :E2
  play :G2
  play :B2
  sleep 1
  play :G1
  play :G2
  sleep 0.5
  play :B0
  play :D2
  play :F2
  sleep 1.5
  play :C2
  play :B1
  play :B0
  sleep 1
  #thirteenth measure
  play :C1
  play :B1
  play :E2
  sleep 1.5
  play :A1
  play :E2
  play :B2
  sleep 2.5
  #fourteenth measure
  play :G1
  play :B1
  play :E2
  play :G2
  sleep 1.5
  play :D2
  play :B1
  play :B0
  sleep 1.5
  play :B0
  play :B1
  play :C2
  sleep 1
  #fifteenth measure
  play :E2
  play :A1
  play :E1
  sleep 1.5
  play :E2
  play :A1
  play :B2
  sleep 1.5
  play :A2
  play :C3
  play :A1
  sleep 1
  #sixteenth measure
  play :E2
  play :G2
  play :B2
  sleep 1
  play :G2
  sleep 0.5
  play :B2
  play :D3
  sleep 1.5
  play :B2
  play :E3
  sleep 1
  2.times do
    #seventeenth measure
    play :A2
    sleep 0.5
    play :A2
    sleep 1.5
    play :A2
    sleep 0.5
    play :C3
    sleep 0.75
    play :C3
    sleep 0.75
    #eighteenth measure
    play :G2
    play :G3
    sleep 1.5
    play :G2
    play :G3
    sleep 0.5
    play :G2
    play :G3
    sleep 0.75
    play :G2
    sleep 0.75
    play :G2
    sleep 0.5
    #ninteenth measure
    play :A2
    sleep 0.5
    play :A2
    sleep 1.5
    play :A2
    sleep 0.5
    play :C3
    sleep 0.75
    play :C3
    sleep 0.75
    #twentieth measure
    play :G2
    play :G3
    sleep 1
    play :G2
    play :G3
    sleep 0.5
    play :G2
    play :G3
    sleep 0.5
    play :G2
    play :E3
    sleep 0.5
    play :G2
    play :E3
    sleep 0.5
    play :G2
    play :C3
    sleep 0.5
    play :G2
    play :C3
    sleep 0.5
    #twenty-first measure
    play :A2
    sleep 0.5
    play :A2
    sleep 1.5
    play :A2
    sleep 0.5
    play :C3
    sleep 0.75
    play :C3
    sleep 0.75
    #twenty-second measure
    play :G2
    play :G3
    sleep 1.5
    play :G2
    play :G3
    sleep 0.5
    play :G2
    play :G3
    sleep 0.75
    play :G2
    sleep 0.75
    play :G2
    sleep 0.5
    #twenty-third measure
    play :A2
    sleep 0.5
    play :A2
    sleep 1.5
    play :A2
    sleep 0.5
    play :C3
    sleep 0.75
    play :C3
    sleep 0.75
    #twenty-fourth measure
    play :G2
    play :G3
    sleep 1
    play :G2
    play :G3
    sleep 0.5
    play :G2
    play :G3
    sleep 0.5
    play :F3
    play :G2
    sleep 0.5
    play :E3
    play :G2
    sleep 0.5
    play :C3
    play :A2
    sleep 0.5
    play :B2
    play :A2
    sleep 0.5
  end
  #twenty-fifth measure
  
  stop
end